name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # Environment variables section
    - name: Build with Gradle Wrapper
      env:
        OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        OPEN_AI_API_URL: ${{ secrets.OPEN_AI_API_URL }}
        SD_API_KEY: ${{ secrets.SD_API_KEY }}
        SD_API_URL: ${{ secrets.SD_API_URL }}
        PPURIO_API_ID: ${{ secrets.PPURIO_API_ID }}
        PPURIO_API_URL: ${{ secrets.PPURIO_API_URL }}
        PPURIO_API_KEY: ${{ secrets.PPURIO_API_KEY }}
        PPURIO_API_FROM: ${{ secrets.PPURIO_API_FROM }}
        AWS_CREDENTIALS_ACCESS_KEY: ${{ secrets.AWS_CREDENTIALS_ACCESS_KEY }}
        AWS_CREDENTIALS_SECRET_KEY: ${{ secrets.AWS_CREDENTIALS_SECRET_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: ./gradlew build -x test

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
